# Loan Amount Slider
LOAN_AMOUNT_MIN = 1000
LOAN_AMOUNT_MAX = 1000000
LOAN_AMOUNT_DEFAULT = 250000

# Down Payment Slider
DOWN_PAYMENT_MIN = 0
DOWN_PAYMENT_MAX = 500000
DOWN_PAYMENT_DEFAULT = 50000

# Interest Rate Slider
INTEREST_RATE_MIN = 5
INTEREST_RATE_MAX = 150
INTEREST_RATE_DEFAULT = 50
INTEREST_RATE_SCALE_FACTOR = 10

# Loan Term Slider
LOAN_TERM_MIN = 1
LOAN_TERM_MAX = 30
LOAN_TERM_DEFAULT = 30

# Extra Payment Slider
EXTRA_PAYMENT_MIN = 0
EXTRA_PAYMENT_MAX = 10000
EXTRA_PAYMENT_DEFAULT = 0
